Repository pegasystems/pega-helm-charts, pull requests merged in 2019-12, with the labels that each got.

#38 deploymentStrategy should not be used with volumeClaimTemplate #37
  charts/pega/README.md
  charts/pega/templates/_pega-deployment.tpl
Labels: enhancement

#41 Defining custom enviroment variables - Issue/#39
  README.md
  charts/pega/README.md
  charts/pega/charts/pegasearch/templates/pega-search-deployment.yaml
  charts/pega/charts/pegasearch/values.yaml
  charts/pega/values.yaml
Labels: documentation, enhancement

#45 Installer chart fixes for Helm 3 (Issue #43)
  charts/pega/charts/installer/templates/pega-install-environment-config.yaml
  charts/pega/charts/installer/templates/pega-upgrade-environment-config.yaml
Labels: bug

#48 Fixes apiVersion for pega_hpa template to support Kubernetes v1.16.x.
  charts/pega/templates/_pega_hpa.tpl
  terratest/src/test/deployment_utility.go
Labels: bug
