Repository pegasystems/pega-helm-charts, pull requests merged in 2020-03, with the labels that each got.

#105 Remove assumptions of a provided PKS cluster
  docs/Deploying-Pega-on-PKS.md
Labels: documentation

#107 Add note about case sensitivity
  charts/pega/README.md
Labels: documentation

#110 Fixing annotation bugs related to ingress changes
  charts/pega/templates/_pega-k8s-ingress.tpl
  charts/pega/templates/_pega-service.tpl
Labels: bug

#117 ISSUE-113: Expose flags to bypass loading engine/assembly classes dur…
  charts/pega/charts/installer/config/prbootstrap.properties.tmpl
  charts/pega/charts/installer/config/setupDatabase.properties.tmpl
  charts/pega/charts/installer/templates/pega-install-environment-config.yaml
  charts/pega/charts/installer/templates/pega-upgrade-environment-config.yaml
  charts/pega/charts/installer/values.yaml
  terratest/src/test/pega/data/expectedPRbootstrap.properties
  terratest/src/test/pega/data/expectedSetupdatabase.properties
Labels: enhancement
