Repository pegasystems/pega-helm-charts, pull requests merged in 2020-01, with the labels that each got.

#60 Configurable imagePullPolicy
  charts/pega/README.md
  charts/pega/charts/pegasearch/templates/pega-search-deployment.yaml
  charts/pega/charts/pegasearch/values.yaml
  charts/pega/templates/_pega-deployment.tpl
Labels: enhancement

#52 Check for null driverUri
  charts/pega/charts/installer/templates/pega-install-environment-config.yaml
  charts/pega/charts/installer/templates/pega-upgrade-environment-config.yaml
  charts/pega/templates/pega-environment-config.yaml
Labels: bug

#64 Add support for custom service and ingress annotations
  charts/pega/README.md
  charts/pega/templates/_pega-k8s-ingress.tpl
  charts/pega/templates/_pega-service.tpl
  charts/pega/templates/pega-tier-service.yaml
Labels: enhancement

#80 Introduced tier name and kubernetes specific DSS settings
  charts/pega/templates/_pega-deployment.tpl
  charts/pega/templates/pega-tier-deployment.yaml
Labels: enhancement

#82 Add support for probe configuration Issue/#65
  charts/pega/README.md
  charts/pega/templates/_helpers.tpl
  charts/pega/templates/_pega-deployment.tpl
  terratest/src/test/deployment_utility.go
Labels: enhancement

#79 Correct curl command to download helm installer
  docs/prepping-local-system-runbook-linux.md
Labels: documentation
