Repository pegasystems/pega-helm-charts, pull requests merged in 2021-07, with the labels that each got.

#316 Issue 294 - java.net.UnknownHostException: pega-search-transport: Name or service not known
  charts/pega/charts/pegasearch/templates/pega-search-transport-service.yaml
Labels: integ-eks

#320 Remove references to port that isn't being used
  charts/pega/config/deploy/server.xml
  terratest/src/test/pega/data/expectedInstallDeployServer.xml
Labels: integ-all

#311 BUG-652949 BUG-656204: Updating CloudK connection pool configuration
  charts/pega/config/deploy/context.xml.tmpl
  terratest/src/test/pega/data/expectedInstallDeployContext.xml
Labels: integ-aks

#312 Add post-upgrade hook to helm installer job in case of upgrade
  charts/pega/charts/installer/templates/_helpers.tpl
  charts/pega/charts/installer/templates/_pega-installer-job.tpl
  charts/pega/charts/installer/templates/pega-installer-config.yaml
  charts/pega/templates/_pega-credentials-secret.tpl
  charts/pega/templates/_pega-registry-secret.tpl
  terratest/src/test/pega/pega-custom-upgrade_test.go
  terratest/src/test/pega/pega-installer-job_test.go
Labels: integ-eks
