Repository pegasystems/pega-helm-charts, pull requests merged in 2021-09, with the labels that each got.

#332 Clarify OpenShift Support Documentation
  README.md
  docs/Deploying-Pega-on-openshift.md
Labels: documentation

#327 Task 1178942 - Need to templatize context.xml.tmpl in different style to support xml parsing
  charts/pega/config/deploy/context.xml.tmpl
  terratest/src/test/pega/data/expectedInstallDeployContext.xml.tmpl
  terratest/src/test/pega/pega-tier-config-web_test.go
  terratest/src/test/pega/pega-tier-config_test.go
Labels: integ-eks, configs

#334 Templatize action validator yaml file
  charts/pega/templates/_pega-action-validate.tpl
  charts/pega/templates/pega-action-validate.yaml
Labels: integ-eks
